version: '2'
services:
  krajono-api:
    build: .
    environment:
      PORT: '5000'
      SHOW_URLS: 'true'
      # KRAJONO_URL: '35.237.231.50'
      KRAJONO_URL: '192.168.99.101'
      META_PORT: '3000'
      META_ENTRY: 'projects'
      META_PORT: '4000'
      META_ENTRY: 'api/projects/'
      COMMENT_PORT: '4100'
      COMMENT_ENTRY: 'comments'
      IMAGE_PORT: '3003'
      IMAGE_ENTRY: 'image'
      AUTHORS_PORT: '7999'
      AUTHORS_ENTRY: 'author'
    ports:
      - '5000:5000'
