version: '2'
services:
  krajono-api:
    build: .
    environment:
      PORT: '5000'
      SHOW_URLS: 'true'
      KRAJONO_URL: '192.168.99.101'
      META_PORT: '3000'
      META_ENTRY: 'projects'
      COMMENT_PORT: '4100'
      COMMENT_ENTRY: 'comments'
      IMAGE_PORT: '3003'
      IMAGE_ENTRY: 'image'
      AUTHOR_PORT: '7999'
      AUTHOR_CREATE: 'create'
      AUTHOR_SEARCH: 'search'
      AUTHOR_AUTHOR: 'author'
    ports:
      - '5000:5000'
