version: '2.1'
services:
  krajono-api:
    build: .
    environment:
      PORT: '5000'
      SHOW_URLS: 'true'
      KRAJONO_URL: 'localhost'
      META_PORT: '3000'
      META_ENTRY: 'projects/'
      COMMENT_PORT: '4100'
      COMMENT_ENTRY: 'comments/'
      VERSION_PORT: '4000'
      VERSION_ENTRY: 'api/proyects'
    ports:
      - '5000:5000'