version: '2'
services:
  krajono-api:
    build: .
    environment:
      PORT: '5000'
      SHOW_URLS: 'true'
      #KRAJONO_URL: '192.168.99.101'
      KRAJONO_URL: '35.247.5.197'
      META_PORT: '3000'
      META_ENTRY: 'projects'
      VERSION_PORT: '4000'
      VERSION_ENTRY: 'api/projects/'
      COMMENT_PORT: '4100'
      COMMENT_ENTRY: 'comments'
      IMAGE_PORT: '3003'
      IMAGE_ENTRY: 'image'
      AUTHORS_PORT: '7999'
      AUTHORS_ENTRY: 'author'

      USERS_URL: '35.247.48.230'
      USERS_PORT: '3009'
      USERS_ENTRY: ''

      AUTH_URL: '35.247.48.230'
      AUTH_PORT: '3009'
      AUTH_ENTRY: 'ldap'
    ports:
      - '5000:5000'
