version: '2.1'
services:
  krajono-api:
    build: .
    environment:
      PORT: '5000'
      SHOW_URLS: 'true'
      KRAJONO_URL: '192.168.99.101'
      META_PORT: '3000'
      META_ENTRY: 'projects/'
      COMMENT_PORT: '4100'
      COMMENT_ENTRY: 'comments/'
      IMAGE_PORT: '3003'
      IMAGE_ENTRY: 'image'
    ports:
      - '5000:5000'
